{
'aaa': ['aaa'],
'aah': ['aah'],
'aar': ['aar', 'ara'],
'aas': ['aas'],
'aab': ['aba', 'baa'],
'abb': ['abb'],
'abc': ['abc', 'cab'],
'abm': ['abm', 'bam', 'mba'],
'abo': ['abo', 'boa'],
'abs': ['abs', 'bas', 'sba'],
'aby': ['aby', 'bay'],
'acc': ['acc'],
'ace': ['ace', 'aec'],
'acs': ['acs', 'cas', 'sac'],
'act': ['act', 'cat'],
'aad': ['ada'],
'add': ['add', 'dad'],
'ade': ['ade', 'dea'],
'adh': ['adh', 'dah'],
'ado': ['ado'],
'adp': ['adp', 'pad', 'pda'],
'ads': ['ads', 'das', 'sad'],
'adz': ['adz'],
'afl': ['afl'],
'afp': ['afp'],
'aft': ['aft', 'atf', 'fat'],
'aag': ['aga'],
'aeg': ['age'],
'ago': ['ago', 'gao', 'goa'],
'ags': ['ags', 'gas', 'gsa', 'sag'],
'adi': ['aid', 'dia', 'ida'],
'ail': ['ail', 'ali'],
'aim': ['aim'],
'air': ['air', 'ira'],
'ais': ['ais', 'ias'],
'aix': ['aix'],
'aks': ['aks', 'ask', 'kas'],
'aku': ['aku', 'auk'],
'aal': ['ala'],
'abl': ['alb', 'lab'],
'ael': ['ale', 'ela', 'lea'],
'alp': ['alp', 'lap', 'pal'],
'als': ['als', 'asl', 'las'],
'alt': ['alt', 'lat'],
'adm': ['amd', 'dam', 'mad'],
'amp': ['amp', 'map'],
'ams': ['ams', 'mas', 'sam'],
'aan': ['ana'],
'aen': ['ane'],
'agn': ['ang', 'gan', 'nag', 'nga'],
'ain': ['ani'],
'ano': ['ano'],
'ans': ['ans', 'nas', 'nsa'],
'ant': ['ant', 'tan'],
'anu': ['anu'],
'acp': ['apc', 'cap', 'cpa', 'pac'],
'aep': ['ape', 'epa', 'pea'],
'apr': ['apr', 'arp', 'par', 'rap'],
'apt': ['apt', 'atp', 'pat', 'tap'],
'abr': ['arb', 'bar', 'bra'],
'acr': ['arc', 'car'],
'akr': ['ark'],
'amr': ['arm', 'mar', 'ram'],
'ars': ['ars', 'ras'],
'art': ['art', 'rat', 'tar'],
'ahs': ['ash'],
'aps': ['asp', 'pas', 'psa', 'sap', 'spa'],
'ass': ['ass', 'sas', 'ssa'],
'aet': ['ate', 'eat', 'eta', 'tea'],
'amt': ['atm', 'mat', 'tam'],
'ast': ['ats', 'sat', 'tas', 'tsa'],
'acu': ['auc', 'uca'],
'agu': ['aug'],
'amu': ['aum', 'uma'],
'asu': ['aus', 'usa'],
'aov': ['avo', 'ova'],
'asv': ['avs', 'vas'],
'aew': ['awe'],
'alw': ['awl', 'law'],
'anw': ['awn', 'wan'],
'aex': ['axe'],
'asx': ['axs', 'sax'],
'ary': ['ayr', 'ray', 'rya'],
'aoz': ['azo'],
'asz': ['azs'],
'atz': ['azt'],
'abd': ['bad', 'dab', 'dba'],
'abg': ['bag', 'gab'],
'abi': ['bai'],
'abn': ['ban', 'nab'],
'abp': ['bap'],
'abt': ['bat', 'tab'],
'bbl': ['bbl'],
'bbs': ['bbs'],
'bce': ['bce'],
'bds': ['bds', 'dbs'],
'bde': ['bed', 'deb'],
'bee': ['bee'],
'beg': ['beg', 'geb'],
'bel': ['bel'],
'ben': ['ben', 'ebn', 'nbe', 'neb'],
'bes': ['bes', 'bse', 'ebs', 'sbe', 'seb'],
'bet': ['bet'],
'bey': ['bey', 'bye'],
'bhs': ['bhs', 'hbs'],
'bbi': ['bib'],
'bdi': ['bid'],
'bgi': ['big', 'gib'],
'bin': ['bin', 'nib'],
'bis': ['bis', 'sib'],
'bit': ['bit', 'tib'],
'biz': ['biz', 'zib'],
'abj': ['bja', 'jab'],
'bjs': ['bjs'],
'bks': ['bks', 'kbs'],
'blt': ['blt'],
'bim': ['bmi', 'mib'],
'bmr': ['bmr'],
'bms': ['bms', 'mbs', 'msb'],
'bns': ['bns', 'nbs'],
'bbo': ['bob'],
'bdo': ['bod'],
'bgo': ['bog', 'gob'],
'boo': ['boo'],
'bop': ['bop', 'pob'],
'bos': ['bos', 'obs', 'sob'],
'bot': ['bot'],
'bow': ['bow'],
'box': ['box'],
'boy': ['boy', 'yob'],
'bhp': ['bph'],
'bip': ['bpi', 'pib'],
'bmp': ['bpm'],
'bps': ['bps', 'pbs'],
'brs': ['brs', 'rbs'],
'bss': ['bss', 'sbs'],
'btu': ['btu', 'tub'],
'bdu': ['bud', 'dub'],
'bgu': ['bug'],
'bmu': ['bum'],
'bnu': ['bun', 'nub'],
'bru': ['bur', 'rub'],
'bsu': ['bus', 'sub'],
'buy': ['buy'],
'bdv': ['bvd'],
'brw': ['bwr'],
'bsw': ['bws', 'sbw', 'wbs'],
'acd': ['cad'],
'acm': ['cam', 'mac'],
'acw': ['caw', 'wac'],
'acy': ['cay'],
'bcc': ['cbc'],
'bcr': ['cbr', 'rbc'],
'ccc': ['ccc'],
'ccs': ['ccs'],
'ccd': ['cdc'],
'cds': ['cds', 'dcs', 'scd'],
'ceo': ['ceo'],
'cer': ['cer'],
'ces': ['ces', 'cse', 'ecs', 'sec'],
'ccf': ['cfc', 'fcc'],
'cfo': ['cfo'],
'cfs': ['cfs', 'fcs'],
'cgs': ['cgs', 'gcs'],
'chi': ['chi'],
'aci': ['cia'],
'cdi': ['cid', 'dci'],
'cim': ['cim'],
'cio': ['cio'],
'cis': ['cis', 'ics', 'sic'],
'cdj': ['cjd'],
'cil': ['cli'],
'cls': ['cls'],
'clv': ['clv'],
'clx': ['clx', 'cxl', 'xcl'],
'bcm': ['cmb'],
'cms': ['cms', 'mcs', 'msc'],
'cmv': ['cmv'],
'cns': ['cns', 'ncs', 'nsc'],
'bco': ['cob'],
'cdo': ['cod', 'doc'],
'cgo': ['cog'],
'clo': ['col'],
'cno': ['con', 'noc'],
'coo': ['coo'],
'cop': ['cop'],
'cos': ['cos'],
'cot': ['cot', 'oct', 'otc'],
'cow': ['cow'],
'cox': ['cox'],
'coy': ['coy'],
'cip': ['cpi', 'pic'],
'cpr': ['cpr', 'crp', 'prc'],
'cps': ['cps', 'pcs'],
'cpu': ['cpu', 'cup'],
'cor': ['cro', 'roc'],
'crs': ['crs'],
'crt': ['crt'],
'cry': ['cry'],
'css': ['css', 'scs'],
'cst': ['cst', 'cts', 'tcs'],
'cct': ['ctc'],
'bcu': ['cub'],
'cdu': ['cud'],
'ceu': ['cue'],
'clu': ['cul'],
'cmu': ['cum'],
'cru': ['cur'],
'csu': ['cus'],
'ctu': ['cut', 'utc'],
'acv': ['cva', 'vac'],
'csv': ['cvs'],
'cmw': ['cwm'],
'ctw': ['cwt', 'wtc'],
'cvx': ['cxv', 'xcv'],
'cxx': ['cxx'],
'adg': ['dag', 'gad'],
'adk': ['dak'],
'adl': ['dal', 'lad'],
'adt': ['dat', 'tad'],
'adw': ['daw', 'wad'],
'ady': ['day'],
'cdd': ['ddc'],
'ddi': ['ddi'],
'dds': ['dds'],
'ddt': ['ddt'],
'cde': ['dec'],
'dde': ['ded', 'edd'],
'den': ['den', 'end'],
'der': ['der', 'red'],
'des': ['des', 'eds'],
'dew': ['dew', 'wed'],
'dgs': ['dgs', 'gds'],
'dei': ['die', 'ied'],
'dgi': ['dig', 'igd'],
'dim': ['dim', 'mdi', 'mid'],
'din': ['din'],
'dip': ['dip', 'idp', 'pid'],
'dis': ['dis', 'ids'],
'dit': ['dit'],
'dix': ['dix'],
'djs': ['djs'],
'dgk': ['dkg'],
'dkl': ['dkl'],
'dkm': ['dkm'],
'del': ['dle', 'eld', 'led'],
'dls': ['dls', 'dsl', 'lsd'],
'ddm': ['dmd'],
'dms': ['dms', 'mds'],
'dmz': ['dmz'],
'adn': ['dna', 'nad'],
'ddo': ['dod', 'odd'],
'deo': ['doe', 'edo', 'ode', 'oed'],
'dgo': ['dog', 'god'],
'dho': ['doh', 'hod'],
'dio': ['doi', 'ido'],
'djo': ['doj'],
'dlo': ['dol', 'old'],
'dos': ['dos', 'ods', 'sod'],
'dot': ['dot', 'tod'],
'dhp': ['dph', 'phd'],
'dps': ['dps', 'pds'],
'dry': ['dry'],
'dss': ['dss', 'sds'],
'dst': ['dts', 'std'],
'ddu': ['dud'],
'deu': ['due'],
'dgu': ['dug'],
'diu': ['dui', 'iud'],
'dnu': ['dun'],
'dou': ['duo'],
'ddv': ['dvd'],
'dey': ['dye'],
'dsy': ['dys'],
'aer': ['ear', 'era'],
'aes': ['eas', 'sea'],
'bbe': ['ebb'],
'bev': ['ebv'],
'cce': ['ecc'],
'cef': ['ecf'],
'ceg': ['ecg'],
'cek': ['eck'],
'cem': ['ecm'],
'cet': ['ect', 'tce', 'tec'],
'dep': ['edp'],
'cee': ['eec'],
'eeg': ['eeg', 'gee'],
'eel': ['eel', 'lee'],
'ees': ['ees', 'ese', 'see'],
'eff': ['eff'],
'eft': ['eft', 'etf', 'fet'],
'egg': ['egg'],
'ego': ['ego'],
'efh': ['ehf'],
'bei': ['eib'],
'egk': ['ekg', 'keg'],
'efl': ['elf'],
'ekl': ['elk', 'lek'],
'ell': ['ell'],
'elm': ['elm', 'lem'],
'eln': ['eln', 'enl'],
'els': ['els', 'les', 'sle'],
'efm': ['emf'],
'egm': ['emg', 'gem', 'meg'],
'ems': ['ems', 'esm', 'mes'],
'emu': ['emu'],
'een': ['ene', 'nee'],
'ens': ['ens', 'nes', 'sen'],
'eno': ['eon', 'neo', 'one'],
'eos': ['eos'],
'eip': ['epi', 'pei', 'pie'],
'eqs': ['eqs', 'esq'],
'egr': ['erg'],
'enr': ['ern'],
'err': ['err'],
'ers': ['ers', 'esr', 'res'],
'ert': ['ert', 'ret'],
'eps': ['esp', 'pes', 'sep'],
'ess': ['ess', 'ses', 'sse'],
'est': ['est', 'set', 'tes'],
'det': ['etd', 'ted'],
'esu': ['eus', 'sue', 'use'],
'eev': ['eve'],
'esv': ['evs', 'ves'],
'eew': ['ewe', 'wee'],
'esw': ['ews', 'sew'],
'esx': ['exs', 'sex', 'xes'],
'eey': ['eye'],
'eoz': ['ezo'],
'aaf': ['faa'],
'abf': ['fab'],
'adf': ['fad', 'fda'],
'aef': ['fae'],
'afg': ['fag'],
'afn': ['fan'],
'afo': ['fao', 'oaf'],
'afq': ['faq'],
'afr': ['far', 'raf'],
'afs': ['fas'],
'afx': ['fax'],
'afy': ['fay'],
'bfi': ['fbi', 'fib'],
'dfr': ['fdr', 'rfd'],
'bef': ['feb'],
'def': ['fed'],
'eef': ['fee'],
'efn': ['fen'],
'efs': ['fes'],
'efy': ['fey'],
'efz': ['fez'],
'afh': ['fha'],
'fgi': ['fig'],
'fin': ['fin'],
'fir': ['fir', 'fri'],
'fit': ['fit'],
'fix': ['fix'],
'fls': ['fls', 'lfs'],
'flu': ['flu', 'ful'],
'fly': ['fly'],
'fms': ['fms', 'mfs'],
'bfo': ['fob'],
'efo': ['foe'],
'fgo': ['fog'],
'fop': ['fop'],
'fos': ['fos'],
'fox': ['fox'],
'dfp': ['fpd'],
'fps': ['fps', 'psf', 'spf'],
'fgr': ['frg'],
'frs': ['frs', 'rfs'],
'fry': ['fry'],
'bfs': ['fsb'],
'fhs': ['fsh', 'hfs', 'shf'],
'fss': ['fss'],
'cft': ['ftc'],
'fot': ['fto', 'oft'],
'fpt': ['ftp'],
'fst': ['fts'],
'fgu': ['fug'],
'fnu': ['fun'],
'fru': ['fur', 'ruf'],
'fsw': ['fws'],
'agg': ['gag'],
'agl': ['gal', 'lag'],
'agm': ['gam', 'mag'],
'agp': ['gap', 'gpa'],
'agr': ['gar', 'rag'],
'agt': ['gat', 'tag'],
'agy': ['gay'],
'bgs': ['gbs'],
'acg': ['gca'],
'dgp': ['gdp'],
'egl': ['gel', 'leg'],
'egn': ['gen'],
'egs': ['ges'],
'egt': ['get', 'teg'],
'bgh': ['ghb'],
'ghq': ['ghq'],
'ghz': ['ghz'],
'agi': ['gia', 'iga'],
'ggi': ['gig', 'igg'],
'gin': ['gin'],
'gip': ['gip', 'pig'],
'gis': ['gis', 'igs'],
'git': ['git'],
'gms': ['gms', 'mgs', 'msg'],
'gmt': ['gmt'],
'gnp': ['gnp'],
'gnu': ['gnu', 'gun', 'ngu'],
'goo': ['goo'],
'gop': ['gop', 'gpo'],
'gos': ['gos'],
'got': ['got', 'tog'],
'goy': ['goy'],
'gps': ['gps'],
'grs': ['gsr', 'rgs'],
'gss': ['gss', 'sgs'],
'giu': ['gui'],
'gmu': ['gum', 'mug'],
'gru': ['gur', 'rug'],
'gsu': ['gus'],
'gtu': ['gut', 'tug'],
'guy': ['guy'],
'gmy': ['gym', 'myg'],
'gpy': ['gyp'],
'gsy': ['gys'],
'agh': ['hag'],
'ahj': ['haj'],
'ahm': ['ham'],
'ahn': ['han'],
'aho': ['hao'],
'ahp': ['hap'],
'aht': ['hat'],
'ahw': ['haw'],
'ahy': ['hay'],
'cgh': ['hcg'],
'dhl': ['hdl'],
'ehl': ['hel'],
'ehm': ['hem'],
'ehn': ['hen'],
'ehp': ['hep'],
'ehs': ['hes'],
'eht': ['het'],
'ehw': ['hew'],
'ehx': ['hex'],
'cfh': ['hfc'],
'ghs': ['hgs'],
'hhs': ['hhs'],
'dhi': ['hid'],
'ehi': ['hie'],
'hin': ['hin', 'inh', 'nih'],
'hip': ['hip', 'phi'],
'hit': ['hit'],
'hiv': ['hiv'],
'hls': ['hls', 'lhs'],
'hmo': ['hmo', 'mho', 'ohm'],
'hms': ['hms', 'msh'],
'dhn': ['hnd'],
'hns': ['hns', 'nhs'],
'bho': ['hob'],
'eho': ['hoe'],
'gho': ['hog'],
'hop': ['hop'],
'hos': ['hos', 'ohs', 'soh'],
'hot': ['hot', 'tho'],
'hoy': ['hoy'],
'hps': ['hps', 'phs'],
'hqs': ['hqs'],
'hrs': ['hrs', 'rhs'],
'hrt': ['hrt', 'trh'],
'hss': ['hss'],
'ahu': ['hua'],
'bhu': ['hub'],
'dhu': ['hud'],
'ehu': ['hue'],
'ghu': ['hug'],
'hmu': ['hum'],
'hnu': ['hun'],
'hsu': ['hus'],
'htu': ['hut'],
'hsz': ['hzs'],
'aai': ['iaa'],
'bio': ['ibo', 'obi'],
'cci': ['icc'],
'cei': ['ice'],
'ciu': ['icu'],
'ciy': ['icy'],
'dfi': ['idf'],
'eir': ['ier', 'ire'],
'eis': ['ies'],
'cfi': ['ifc'],
'egi': ['ige'],
'gim': ['igm'],
'iii': ['iii'],
'iis': ['iis', 'isi'],
'eik': ['ike'],
'ikl': ['ilk'],
'ill': ['ill'],
'ilo': ['ilo', 'iol', 'oil'],
'ils': ['ils', 'lis'],
'ilx': ['ilx', 'ixl', 'lxi', 'xli'],
'fim': ['imf'],
'imo': ['imo'],
'imp': ['imp'],
'imu': ['imu'],
'cin': ['inc'],
'ikn': ['ink', 'kin'],
'inn': ['inn'],
'inr': ['inr'],
'ins': ['ins', 'nis', 'sin'],
'ino': ['ion', 'oni'],
'iop': ['iop', 'ipo', 'poi'],
'ios': ['ios', 'ois'],
'iou': ['iou'],
'ips': ['ips', 'pis', 'psi', 'sip'],
'ipv': ['ipv', 'ivp', 'vip'],
'iqs': ['iqs', 'qis'],
'ikr': ['irk'],
'irs': ['irs', 'ris', 'sir'],
'ims': ['ism', 'mis'],
'iss': ['iss', 'sis'],
'aiv': ['iva'],
'isv': ['ivs', 'vis'],
'ivy': ['ivy'],
'iow': ['iwo'],
'isw': ['iws', 'wis'],
'iww': ['iww'],
'cix': ['ixc', 'xci'],
'isx': ['ixs', 'six', 'xis'],
'agj': ['jag'],
'ajk': ['jak'],
'ajm': ['jam'],
'ajn': ['jan'],
'ajp': ['jap'],
'ajr': ['jar', 'jra', 'raj'],
'ajt': ['jat'],
'ajw': ['jaw'],
'ajy': ['jay'],
'ejm': ['jem'],
'ejt': ['jet'],
'ejw': ['jew'],
'fjk': ['jfk'],
'bij': ['jib'],
'gij': ['jig'],
'ijs': ['jis'],
'djn': ['jnd'],
'jnr': ['jnr'],
'bjo': ['job'],
'gjo': ['jog'],
'jot': ['jot'],
'joy': ['joy'],
'jrs': ['jrs'],
'jss': ['jss'],
'gju': ['jug'],
'jtu': ['jut'],
'jsv': ['jvs'],
'akt': ['kat'],
'bko': ['kbo', 'kob'],
'cks': ['kcs'],
'aek': ['kea'],
'bek': ['keb'],
'ekn': ['ken'],
'ekr': ['ker'],
'eky': ['key'],
'bgk': ['kgb'],
'gks': ['kgs'],
'hik': ['khi'],
'hkz': ['khz'],
'bik': ['kib'],
'dik': ['kid'],
'ikp': ['kip'],
'iks': ['kis', 'ski'],
'ikt': ['kit'],
'kkk': ['kkk'],
'kms': ['kms'],
'kor': ['kor'],
'kos': ['kos', 'oks'],
'hkp': ['kph'],
'kps': ['kps'],
'krs': ['krs'],
'kss': ['kss'],
'kst': ['kts', 'tsk'],
'iku': ['kui'],
'ksv': ['kvs'],
'akw': ['kwa'],
'ksw': ['kws'],
'dky': ['kyd'],
'ksy': ['kys', 'sky'],
'acl': ['lac'],
'ahl': ['lah'],
'alm': ['lam'],
'aln': ['lan'],
'alo': ['lao', 'ola'],
'alv': ['lav'],
'alx': ['lax'],
'aly': ['lay'],
'bjl': ['lbj'],
'bls': ['lbs'],
'cdl': ['lcd'],
'clm': ['lcm'],
'dll': ['ldl', 'lld'],
'eil': ['lei', 'lie'],
'elo': ['leo'],
'elr': ['ler'],
'elt': ['let'],
'elu': ['leu'],
'elv': ['lev'],
'ely': ['ley', 'lye'],
'bgl': ['lgb'],
'glv': ['lgv'],
'dil': ['lid'],
'iil': ['lii'],
'iln': ['lin', 'nil'],
'ilp': ['lip'],
'ilr': ['lir'],
'ilt': ['lit'],
'ilv': ['liv', 'lvi'],
'bll': ['llb'],
'llm': ['llm'],
'lms': ['lms', 'mls'],
'blo': ['lob'],
'glo': ['log'],
'loo': ['loo'],
'lop': ['lop', 'plo', 'pol'],
'lot': ['lot'],
'low': ['low', 'owl'],
'lox': ['lox'],
'lnp': ['lpn', 'nlp'],
'lps': ['lps'],
'lrs': ['lrs'],
'lss': ['lss', 'sls'],
'lmt': ['ltm'],
'glu': ['lug'],
'lou': ['luo'],
'lsu': ['lus'],
'lux': ['lux'],
'lsx': ['lxs', 'xls'],
'lvx': ['lxv', 'xlv'],
'lxx': ['lxx'],
'akm': ['mak'],
'amm': ['mam'],
'amn': ['man'],
'amo': ['mao', 'moa'],
'amw': ['maw'],
'amx': ['max'],
'amy': ['may', 'mya', 'yam'],
'bdm': ['mbd'],
'cgm': ['mcg'],
'dem': ['med'],
'eim': ['mei'],
'ekm': ['mek'],
'emm': ['mem'],
'emn': ['men'],
'emq': ['meq'],
'emr': ['mer', 'rem'],
'emt': ['met'],
'emw': ['mew'],
'afm': ['mfa'],
'hmz': ['mhz'],
'ilm': ['mil'],
'imn': ['min', 'nim'],
'imt': ['mit'],
'imx': ['mix'],
'kmo': ['mko'],
'mms': ['mms'],
'mns': ['mns', 'nms'],
'bmo': ['mob', 'omb'],
'dmo': ['mod'],
'lmo': ['mol', 'olm'],
'mmo': ['mom'],
'mno': ['mon'],
'moo': ['moo'],
'mop': ['mop', 'pom'],
'mos': ['mos', 'som'],
'mot': ['mot', 'tom'],
'mow': ['mow', 'wmo'],
'hmp': ['mph'],
'mps': ['mps', 'pms'],
'dmr': ['mrd'],
'imr': ['mri', 'rim'],
'mrs': ['mrs'],
'mss': ['mss', 'sms'],
'mst': ['mst', 'mts', 'stm', 'tms'],
'dmu': ['mud'],
'mmu': ['mum'],
'msu': ['mus', 'sum'],
'mpv': ['mvp'],
'msv': ['mvs'],
'msx': ['mxs'],
'mmy': ['mym'],
'acn': ['nac'],
'ann': ['nan'],
'anp': ['nap', 'npa', 'pan'],
'any': ['nay'],
'bnw': ['nbw', 'wbn'],
'dns': ['nds'],
'cen': ['nec'],
'ent': ['net', 'ten'],
'enw': ['new', 'wen'],
'eny': ['ney', 'yen'],
'bgn': ['ngb'],
'fgn': ['ngf'],
'gno': ['ngo', 'nog'],
'gns': ['ngs'],
'ijn': ['nij'],
'inp': ['nip', 'pin'],
'int': ['nit', 'tin'],
'inx': ['nix'],
'jns': ['njs'],
'mnr': ['nmr'],
'enn': ['nne'],
'nnw': ['nnw'],
'bno': ['nob'],
'dno': ['nod'],
'nno': ['non'],
'nos': ['nos', 'son'],
'nov': ['nov'],
'nox': ['nox'],
'cnp': ['npc'],
'nps': ['nps', 'snp'],
'anr': ['nra', 'ran', 'rna'],
'cnr': ['nrc'],
'lnr': ['nrl'],
'nor': ['nro', 'ron'],
'fns': ['nsf'],
'nss': ['nss', 'sns'],
'nsu': ['nsu', 'nus', 'sun', 'uns', 'usn'],
'nsw': ['nsw', 'nws'],
'hnt': ['nth'],
'nst': ['nts', 'tns'],
'nnu': ['nun'],
'ntu': ['nut', 'tun', 'utn'],
'nsv': ['nvs'],
'nsy': ['nys'],
'nxy': ['nyx'],
'ako': ['oak', 'oka'],
'aor': ['oar', 'ora'],
'aos': ['oas'],
'aot': ['oat', 'tao'],
'aco': ['oca'],
'doo': ['odo'],
'foo': ['ofo'],
'gio': ['oig'],
'noo': ['ono'],
'hoo': ['ooh'],
'ops': ['ops', 'pos', 'sop'],
'opt': ['opt', 'pot', 'pto', 'top'],
'opv': ['opv'],
'bor': ['orb', 'rob'],
'eor': ['ore', 'roe'],
'orr': ['orr'],
'ors': ['ors', 'ros'],
'oss': ['oss', 'sos'],
'oot': ['oto'],
'osv': ['ovs'],
'eow': ['owe', 'woe'],
'osx': ['oxs'],
'app': ['pap'],
'apw': ['paw'],
'apx': ['pax'],
'apy': ['pay', 'pya', 'yap'],
'cpp': ['pcp'],
'cpt': ['pct', 'tcp'],
'dlp': ['pdl'],
'eep': ['pee'],
'egp': ['peg'],
'elp': ['pel'],
'enp': ['pen'],
'epp': ['pep'],
'ept': ['pet'],
'epw': ['pew'],
'cfp': ['pfc'],
'aip': ['pia'],
'ijp': ['pij'],
'ipp': ['pip'],
'ipt': ['pit', 'tip'],
'ipx': ['pix'],
'dkp': ['pkd'],
'kpu': ['pku'],
'flp': ['plf'],
'lpy': ['ply'],
'aop': ['poa'],
'dop': ['pod'],
'eop': ['poe'],
'opp': ['pop'],
'opw': ['pow', 'wop'],
'opx': ['pox'],
'kpp': ['ppk'],
'ppp': ['ppp'],
'npr': ['prn'],
'opr': ['pro'],
'prs': ['prs'],
'pry': ['pry'],
'pss': ['pss'],
'pst': ['pst', 'pts', 'stp'],
'bpu': ['pub'],
'dpu': ['pud'],
'gpu': ['pug'],
'lpu': ['pul'],
'npu': ['pun'],
'ppu': ['pup'],
'psu': ['pus', 'sup', 'ups'],
'ptu': ['put', 'tup'],
'apv': ['pva'],
'cpv': ['pvc'],
'prw': ['pwr'],
'psx': ['pxs'],
'pxy': ['pyx'],
'aqt': ['qat'],
'cdq': ['qcd'],
'deq': ['qed'],
'inq': ['qin'],
'qss': ['qss'],
'mqu': ['qum'],
'adr': ['rad'],
'arw': ['raw', 'war'],
'bir': ['rbi', 'rib'],
'ber': ['reb'],
'efr': ['ref'],
'epr': ['rep'],
'erv': ['rev', 'ver'],
'erx': ['rex', 'xer'],
'dhr': ['rhd'],
'hor': ['rho'],
'dir': ['rid'],
'gir': ['rig'],
'ior': ['rio', 'roi'],
'ipr': ['rip'],
'nrs': ['rns'],
'dor': ['rod'],
'mor': ['rom'],
'ort': ['rot', 'tor'],
'orw': ['row'],
'mpr': ['rpm'],
'rss': ['rss', 'srs'],
'eru': ['rue', 'uer'],
'mru': ['rum'],
'nru': ['run', 'urn'],
'rsu': ['rus', 'sur', 'urs'],
'rtu': ['rut'],
'rsv': ['rvs', 'svr'],
'ery': ['rye'],
'asw': ['saw'],
'asy': ['say'],
'hsy': ['shy'],
'fis': ['sif'],
'ist': ['sit', 'tis'],
'lsy': ['sly'],
'los': ['sol'],
'ost': ['sot'],
'osu': ['sou'],
'osw': ['sow'],
'osy': ['soy'],
'psy': ['spy'],
'sss': ['sss'],
'ssw': ['ssw', 'sws', 'wss'],
'hst': ['sth', 'ths', 'tsh'],
'sty': ['sty'],
'ssu': ['sus', 'uss'],
'suv': ['suv', 'uvs'],
'ait': ['tai', 'tia'],
'att': ['tat'],
'atu': ['tau', 'uta'],
'atw': ['taw'],
'atx': ['tax'],
'aty': ['tay'],
'bst': ['tbs'],
'dtt': ['tdt'],
'eet': ['tee'],
'ett': ['tet'],
'bht': ['thb'],
'cht': ['thc'],
'dht': ['thd'],
'hmt': ['thm'],
'htz': ['thz'],
'cit': ['tic'],
'eit': ['tie'],
'itt': ['tit'],
'itu': ['tiu'],
'kot': ['tko'],
'clt': ['tlc'],
'lst': ['tls'],
'mtv': ['tmv'],
'fnt': ['tnf'],
'ntt': ['tnt'],
'eot': ['toe'],
'not': ['ton'],
'ott': ['tot'],
'otw': ['tow', 'two', 'wto'],
'oty': ['toy'],
'npt': ['tpn'],
'frt': ['trf'],
'mrt': ['trm'],
'rty': ['try', 'tyr'],
'sst': ['tss'],
'stt': ['tts'],
'mtu': ['tum'],
'ttu': ['tut'],
'tux': ['tux'],
'stv': ['tvs', 'vts'],
'stx': ['txs', 'xts'],
'adu': ['uda'],
'afu': ['ufa'],
'fou': ['ufo'],
'fhu': ['uhf'],
'eku': ['uke'],
'ksu': ['uks'],
'llu': ['ull'],
'ltu': ['ult'],
'mpu': ['ump'],
'nqu': ['unq'],
'dru': ['urd'],
'lru': ['url'],
'etu': ['ute'],
'stu': ['uts'],
'tuu': ['utu', 'uut'],
'buu': ['uub'],
'huu': ['uuh'],
'puu': ['uup'],
'quu': ['uuq'],
'iuz': ['uzi'],
'anv': ['van'],
'arv': ['var'],
'atv': ['vat'],
'crv': ['vcr'],
'dsv': ['vds'],
'duv': ['vdu'],
'egv': ['veg'],
'etv': ['vet'],
'evx': ['vex'],
'fvw': ['vfw'],
'fhv': ['vhf'],
'eiv': ['vie'],
'iiv': ['vii'],
'imv': ['vim'],
'flv': ['vlf'],
'ovw': ['vow'],
'ovx': ['vox'],
'ssv': ['vss'],
'agw': ['wag'],
'aww': ['waw'],
'awx': ['wax'],
'awy': ['way', 'yaw'],
'bcw': ['wbc'],
'bew': ['web'],
'eiw': ['wei'],
'etw': ['wet'],
'giw': ['wig'],
'inw': ['win'],
'itw': ['wit'],
'iwz': ['wiz'],
'dmw': ['wmd'],
'nww': ['wnw'],
'gow': ['wog'],
'kow': ['wok'],
'oow': ['woo'],
'oww': ['wow'],
'mpw': ['wpm'],
'rwy': ['wry'],
'sww': ['wsw'],
'tvw': ['wtv'],
'suw': ['wus'],
'svw': ['wvs'],
'www': ['www'],
'ewy': ['wye', 'yew'],
'swy': ['wys'],
'csx': ['xcs'],
'iix': ['xii'],
'ivx': ['xiv', 'xvi'],
'ixx': ['xix', 'xxi'],
'ssx': ['xss'],
'ctx': ['xtc'],
'svx': ['xvs'],
'sxx': ['xxs'],
'vxx': ['xxv'],
'xxx': ['xxx'],
'xxy': ['xxy'],
'sxy': ['xys'],
'xyy': ['xyy'],
'aky': ['yak'],
'ayy': ['yay'],
'bsy': ['ybs'],
'aey': ['yea'],
'esy': ['yes'],
'ety': ['yet'],
'biy': ['yib'],
'diy': ['yid'],
'iny': ['yin'],
'ipy': ['yip'],
'isy': ['yis'],
'noy': ['yon'],
'rsy': ['yrs'],
'ssy': ['yss'],
'euy': ['yue'],
'agz': ['zag'],
'apz': ['zap'],
'bsz': ['zbs'],
'dvz': ['zdv'],
'aez': ['zea'],
'dez': ['zed'],
'eez': ['zee'],
'enz': ['zen'],
'epz': ['zep'],
'esz': ['zes'],
'giz': ['zig'],
'ipz': ['zip'],
'itz': ['zit'],
'nsz': ['zns'],
'ooz': ['zoo'],
'rsz': ['zrs'],
'ssz': ['zss'],
'suz': ['zus']
}