export const words = {
    "abc": ["cab"],
    "apt": ["apt", "pat", "tap"],
    'aet': ['ate', 'eat', 'eta', 'tea'],
    'aew': ['awe'],
    'aex': ['axe'],
    'abp': ['bap'],
    'obt': ['bot'],
    'cgo': ['cog'],
    'cpu': ['cup'],
    'cyr': ['cry'],
    'idm': ['dim', 'mid'],
    'dlo': ['old'],
    'dey': ['dye'],
    'efl': ['elf'],
    'ekl': ['elk'],
    'ful': ['flu'],
    'xfo': ['fox'],
    'agy': ['gay'],
    'egl': ['gel', 'leg'],
    'ggi': ['gig'],
    'ahm': ['ham'],
    'ahy': ['hay'],
    'hpi': ['hip', 'phi'],
    'ciy': ['icy'],
    'ino': ['ion'],    
    'ikr': ['irk'],
    'agj': ['jag'],
    'ajm': ['jam'],
    'ejm': ['jem'],
    'ejt': ['jet'],
    'ejw': ['jew'],
    'ekn': ['ken'],
    'eky': ['key'],    
    'dik': ['kid'],
    'ikp': ['kip'],
    'aly': ['lay'],
    'ilp': ['lip'],
    'ilt': ['lit'],
    'fot': ['oft'],
  }